name: Release Windows Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true
          
      - name: Show Flutter version
        run: flutter --version
          
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
        
      - name: Get dependencies
        run: |
          flutter pub get
          flutter doctor -v
        
      - name: Build Windows
        run: |
          flutter clean
          flutter build windows --release --verbose
        
      - name: List build directory
        run: dir build\windows\x64\runner\Release
        
      - name: Create ZIP archive
        run: |
          cd build\windows\x64\runner\Release
          Compress-Archive -Path * -DestinationPath ..\..\..\..\flutter_actions_windows.zip
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/flutter_actions_windows.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
